version = 0.1

[default]
[default.global.parameters]
stack_name    = "cloudwatch-apm-demo"
region        = "ap-south-1"

[default.build.parameters]
parallel = true

[default.deploy.parameters]
capabilities      = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3        = true
# s3_prefix = "cloudwatch-apm-demo"   # uncomment to customise S3 prefix
# image_repositories = []
s3_prefix = "cloudwatch-apm-demo"
region = "ap-south-1"
image_repositories = []
